###############################################
### AMAK Data & Control File Writer
### Matt Siskey
### February 2021
###############################################

writeCtl_dusky <- function(dat,y){
  cat(
    "Model_1	# model_name\n",
    "goa_dr_2020.dat	# data_file\n",
    "3	# SrType\n",
    "1977	# styr_rec_est\n",
    "2020	# endyr_rec_est\n",
    "1	# rec_like_type\n",
    "2	# fsh_sel_opt\n",
    "2	# srv1_sel_opt\n",
    "2	# srv2_sel_opt\n",
    "8	# n_fish_sel_ages\n",
    "7	# n_srv1_sel_ages\n",
    "7	# n_srv2_sel_ages\n",
    "5	# ph_Fdev\n",
    "2	# ph_avg_F\n",
    "2	# ph_recdev\n",
    "5	# ph_fish_sel\n",
    "5	# ph_srv1_sel\n",
    "-5	# ph_srv2_sel\n",
    "0.07	# mprior\n",
    "0.05	# cvmprior\n",
    "-4	# ph_m\n",
    "0.9	# steep_prior\n",
    "0.1	# cv_steep_prior\n",
    "-5	# ph_steepness\n",
    "1.5	# sigrprior\n",
    "0.447213595	# cvsigrprior\n",
    "1	# ph_sigr\n",
    "1	# q_srv1prior\n",
    "0.447213595	# cvq_srv1prior\n",
    "3	# ph_q_srv1\n",
    "1	# q_srv2prior\n",
    "0.15	# cvq_srv2prior\n",
    "-3	# ph_q_srv2\n",
    "1991	# yr_catchwt\n",
    "2	# wt_ssqcatch\n",
    "50	# wt_ssqcatch2\n",
    "1	# wt_cpue\n",
    "1.66	# wt_srv1\n",
    "0	# wt_srv2\n",
    "1	# wt_fish_age\n",
    "1	# wt_srv1_age\n",
    "1	# wt_fish_size\n",
    "0	# wt_srv1_size\n",
    "0	# wt_srv2_size\n",
    "1	# wt_rec_var\n",
    "1	# wt_sel_reg_fish\n",
    "1	# wt_sel_reg_srv1\n",
    "0	# wt_sel_reg_srv2\n",
    "1	# wt_sel_dome_fish\n",
    "1	# wt_sel_dome_srv1\n",
    "0	# wt_sel_dome_srv2\n",
    "2	# wt_fmort_reg\n",
    "1	# wt_avg_sel\n",
    "1	# ph_logsurv\n",
    "3	# initial_LMR\n",
    "0	# wt_Rzero\n",
    "6	# agesamplestyle\n",
    "6	# lensamplestyle\n",
    "0.674103409824753	# yieldratio\n",
    CompDist,"# CompDist (1=multinomial, 2=dirichlet-multinomial)\n",
    log_theta_prior,"# log_theta_srv1_age_prior (rec: 0.5)\n",
    cv_theta_prior,"# cv_theta_srv1_age_prior (rec: 0.05)\n",
    ph_theta,"# ph_theta_srv1_age (rec: 2; set to negative value to turn off estimation of theta)\n",
    file=dat,sep=" ")
}

# file=dat,append=TRUE,sep=" ")
